/*****+*--*-***-*--*---*-*-*-****-*--***-***--******************************
 *
 *  Lab #: 12
 *
 *  Academic Integrity Statement:
 *
 *  I have not used source code obtained from any other unauthorized source, 
 *  either modified or unmodified.  Neither have I provided access to my code 
 *  to another. The effort I am submitting is my own original work.
 *
 *  Program Description: This program accepts a user inputted seed and
 *  array size for randomization of numbers which represent the origin of a
 *  sound. The program then changes the array to either be a negative one,
 *  or the modulus ten of the number if it is a multiple of nine. Next,
 *  the program calculates possible locations by checking if the indices
 *  of values which are not negative one, and adding/subtracting the values
 *  from their respective indices, as long as the numbers are within array
 *  bounds. The program finally prints these resulting numbers.
 *
 ******+*--*-***-*--*---*-*-*-****-*--***-***--*****************************/
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#define UPPER 999
#define LOWER 0

void inputSeed(int*);
void inputSize(int*);
void arrayFill(int[],int);
void changeVals(int[],int[],int);
void locationCalc(int[],int[],int[],int);
void output(int[],int);

int main(void)
{
  int seed; // random seed value
  int dataSize; // desired data set size
  int *dataArray; // array of data values
  int *indexArray; // array of index values
  int *locationVec; // array for the location of the desired value

  inputSeed(&seed);
  inputSize(&dataSize);

  srand(seed);

  dataArray = (int*)malloc(sizeof(int) * dataSize);
  indexArray = (int*)malloc(sizeof(int) * dataSize);
  locationVec = (int*)malloc(sizeof(int) * dataSize);

  arrayFill(dataArray,dataSize);

  changeVals(dataArray,indexArray,dataSize);

  locationCalc(dataArray,indexArray,locationVec,dataSize);

  output(locationVec,dataSize);

  return 0;
}

/*****+----*-----**----**--*---*--*--***-***--******************************
*
*  Function Information
*
*  Name of Function: inputSeed
*
*  Function Return Type: void
*
*  Parameters (list data type, name, and comment one per line):
*    1. int *, seed, random seed generated by user
*    2.
*    3.
*
*  Function Description: Generates a random data set based on the user's input
*
******+----*-----**----**--*---*--*--***-***--*****************************/

void inputSeed(int* seed)
{
  do
  {
    printf("Enter seed value -> ");
    scanf("%d",seed);

    if(*seed <= 0) // prints error message if the seed is less than or equal to zero
    {
      printf("\n");
      printf("Error! Positive seed values only!!\n");
      printf("\n");
    }

  }while(*seed <= 0);

}

/*****+-*-***-*-**-----**--*---*--*--***-***--******************************
*
*  Function Information
*
*  Name of Function: inputSize
*
*  Function Return Type: void
*
*  Parameters (list data type, name, and comment one per line):
*    1. int*, dataSize, desired data set size
*    2.
*    3.
*
*  Function Description: Stores user's desired data set size
*
******+-*-***-*-**-----**--*---*--*--***-***--*****************************/

void inputSize(int* dataSize)
{

  do
  {
    printf("Enter desired data set size -> ");
    scanf("%d",dataSize);

    if(*dataSize <= 0)
    {
      printf("\n");
      printf("Error! Positive values only!!\n");
      printf("\n");
    }

  }while(*dataSize <= 0);

}

/*****+-*-***-*-**-----**--*---*--*--***-***--******************************
*
*  Function Information
*
*  Name of Function: arrayFill
*
*  Function Return Type: void
*
*  Parameters (list data type, name, and comment one per line):
*    1. int [], array, array of values
*    2. int, size, desired size of the array
*    3.
*
*  Function Description: fills the array with the random values generated for the required size
*
******+-*-***-*-**-----**--*---*--*--***-***--*****************************/

void arrayFill(int array[],int size)
{
  int i; // index

  for(i = 0;i < size;i++)
  {
    array[i] = rand() % (UPPER - LOWER + 1) + LOWER;
  }
}

/*****+-*-***-*-**-----**--*---*--*--***-***--******************************
*
*  Function Information
*
*  Name of Function: changeVals
*
*  Function Return Type: void
*
*  Parameters (list data type, name, and comment one per line):
*    1. int [], array, array of values
*    2. int [], indexArray, creates an array that's value gets updated if the sound is heard for the given location
*    3. int, size, desired size of the array
*
*  Function Description: changes the values of both arrays to represent locations of the sounds origin
*
******+-*-***-*-**-----**--*---*--*--***-***--*****************************/

void changeVals(int array[],int indexArray[],int size)
{
  int i; // index

  for(i = 0;i < size;i++)
  {
    if(array[i] % 9 == 0)
    { 
      array[i] = array[i] % 10;
      indexArray[i] = i;
    }
    else
    {
      array[i] = -1;
      indexArray[i] = -1;
    }
  }
}

/*****+-*-***-*-**-----**--*---*--*--***-***--******************************
*
*  Function Information
*
*  Name of Function: locationCalc
*
*  Function Return Type: void
*
*  Parameters (list data type, name, and comment one per line):
*    1. int [], array, edited array of values
*    2. int [], indexArray, array with updated sound distances
*    3. int [], locationArray, array that completely calculates locations
*    4. int, size, size of the arrays
*
*  Function Description: calculates the locations of the sound origination and puts it in an array
*
******+-*-***-*-**-----**--*---*--*--***-***--*****************************/

void locationCalc(int array[],int indexArray[],int locationArray[],int size)
{
  int i; //index

  for(i = 0;i < size;i++)
  {
    if(array[i] != -1 )
    {
      if(array[i] + indexArray[i] < size)
      {
        locationArray[array[i] + indexArray[i]] = 1;
      }

      if(indexArray[i] - array[i] >= 0)
      {
        locationArray[indexArray[i] - array[i]] = 1;
      }
    }

  }
}

/*****+-*-***-*-**-----**--*---*--*--***-***--******************************
*
*  Function Information
*
*  Name of Function: output
*
*  Function Return Type: void
*
*  Parameters (list data type, name, and comment one per line):
*    1. int [], array, array of data values
*    2. int, size, size of the desired data set
*    3.
*
*  Function Description: outputs the final locations of the origin of the sound
*
******+-*-***-*-**-----**--*---*--*--***-***--*****************************/

void output(int array[], int size)
{
  int i; // index
  int count; // variable used to determine if there is a sound

  count = 0;

  printf("\nPossible locations:");

  for(i = 0;i < size;i++)
  {
    if(array[i] == 1)
    {
      printf(" %d",i);
      count++;
    }
  }

  if(count == 0)
  {
    printf(" None");
  }
  printf("\n");
}
